# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
config.vm.boot_timeout = 600
# === Ensure SSH keys exist ===
  require 'fileutils'
  ssh_dir = File.expand_path("~/.ssh")
  private_key = File.join(ssh_dir, "id_rsa_vagrant")
  public_key  = "#{private_key}.pub"

  FileUtils.mkdir_p(ssh_dir)

  unless File.exist?(private_key) && File.exist?(public_key)
    puts "==> SSH key pair not found. Generating new keys at #{private_key}..."
    system("ssh-keygen -t rsa -b 4096 -f \"#{private_key}\" -N \"\"")
  end
  config.ssh.insert_key = true
  
#   config.vm.provision "shell", path: "provision.sh"

  # DB VM
  config.vm.define "db" do |db|
    db.vm.box = "bento/ubuntu-22.04"
    db.vm.hostname = "db-vm"
    db.vm.network "private_network", ip: "192.168.56.12"
    db.vm.network "forwarded_port", guest: 8082, host: 8082

    db.vm.synced_folder "./h2-data", "/vagrant/h2-data", create: true

    # Copy custom SSH public key
#    db.vm.provision "file",  source: File.expand_path("~/.ssh/id_rsa_vagrant.pub"), destination: "/home/vagrant/.ssh/authorized_keys"
#    db.vm.provision "shell", inline: <<-SHELL
#      chmod 600 /home/vagrant/.ssh/authorized_keys
#      chmod 700 /home/vagrant/.ssh
#    SHELL

    # Provision Script
    #db.vm.provision "shell", path: "provision.sh"

 #   Automation Script for db
 #   db.vm.provision "shell",
 #   env: {
 #   "VM_TYPE" => "db",
 #   "CLONE_REPOS" => "true",
 #   "BUILD_APPS" => "false",
 #   "START_SERVICES" => "true"
 #  },
 #   inline: <<-SHELL
 #   cd /vagrant
 #   ./automate_apps.sh
 #  SHELL

 db.vm.provision "ansible_local" do |ans|
  ans.playbook = "/vagrant/ansible/site.yml"
  ans.inventory_path = "/vagrant/ansible/hosts.ini"
  ans.limit = "db"
  ans.become = true
end

  end

  # App VM
  config.vm.define "app" do |app|
    app.vm.box = "bento/ubuntu-22.04"
    app.vm.hostname = "app-vm"
    app.vm.network "forwarded_port", guest: 8080, host: 8080   # for REST API
    app.vm.network "private_network", ip: "192.168.56.11"

    # Copy custom SSH public key
#    app.vm.provision "file", source: File.expand_path("~/.ssh/id_rsa_vagrant.pub"), destination: "/home/vagrant/.ssh/authorized_keys"
#    app.vm.provision "shell", inline: <<-SHELL
#      chmod 600 /home/vagrant/.ssh/authorized_keys
#      chmod 700 /home/vagrant/.ssh
#    SHELL

    # Provision Script
#   app.vm.provision "shell", path: "provision.sh"

    # Automation Script for app
#    app.vm.provision "shell", inline: <<-SHELL
#      cd /vagrant
#      export VM_TYPE=app
#      export CLONE_REPOS=true
#      export BUILD_APPS=true
#      export START_SERVICES=true
#      ./automate_apps.sh
#    SHELL

app.vm.provision "ansible_local" do |ans|
  ans.playbook = "/vagrant/ansible/site.yml"
  ans.inventory_path = "/vagrant/ansible/hosts.ini"
  ans.limit = "app"
  ans.become = true
end
  end
end