# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "vagrant-machine"

  # Private network to access applications on the host  
  config.vm.network "private_network", ip: "192.168.56.10"
  
  # Provisioning: install Git, JDK, Maven, Gradle
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git openjdk-17-jdk maven unzip curl
    # Install Gradle manually
    wget https://services.gradle.org/distributions/gradle-8.3-bin.zip -P /tmp
    unzip -d /opt/gradle /tmp/gradle-8.3-bin.zip
    echo "export PATH=\$PATH:/opt/gradle/gradle-8.3/bin" >> /etc/profile
  SHELL
end
