# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "vagrant-machine"
  config.vm.network "forwarded_port", guest: 8080, host: 8080   # for REST API
  config.vm.network "forwarded_port", guest: 5000, host: 5000   # for simple chat
  config.vm.network "private_network", ip: "192.168.56.10"

   # Provision Script
   config.vm.provision "shell", path: "provision.sh"

   # Automation Script for apps
   config.vm.provision "shell", inline: <<-SHELL
     export CLONE_REPOS=true
     export BUILD_APPS=true
     export START_SERVICES=true
     ./automate_apps.sh
   SHELL
end